# fly.toml app configuration file generated for gpm-recipe-app on 2023-04-26T14:40:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gpm-recipe-app"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
